# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/master/kas/schema-kas.json

header:
  version: 14

distro: nodistro

defaults:
  repos:
    branch: master

repos:
  bitbake:
    url: https://github.com/openembedded/bitbake
    layers:
      .: disabled

  openembedded-core:
    url: https://github.com/openembedded/openembedded-core
    layers:
      meta:

  meta-ai:

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded
    layers:
      meta-oe:

local_conf_header:
  base: |
    INHERIT += "buildstats buildstats-summary"
    INHERIT += "buildhistory"
    INHERIT += "rm_work"
  diskmon: |
    # Protect against disk fulling up and produce a clear error if that happens
    BB_DISKMON_DIRS ??= "\
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},10G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},1G,1K \
      HALT,/tmp,10M,1K"

machine: unset

target:
  - tensorflow-lite
