name: Build on PR
run-name: "${{ github.base_ref }}: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'README'
      - 'SECURITY.md'

permissions:
  contents: read

jobs:
  event-file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Event File
          path: ${{ github.event_path }}
          if-no-files-found: error

  pr-to-workflow-dependency:
    name: "PR to workflow dependency"
    permissions:
      actions: read
      contents: read
      pull-requests: read
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/qswat-reusable-pr-to-workflow-dependency.yml@0f1b47d0eb808a4a2142db40bf3d86becc8c02da
    with:
      workflow_id: ${{ github.run_id }}
      run_attempt: ${{ github.run_attempt }}
      pr_number: ${{ github.event.pull_request.number }}

  build-pr:
    permissions:
      actions: read
      contents: read
      packages: read
    uses: ./.github/workflows/build-openembedded.yml
